#!/usr/bin/env python


import rospy
from std_msgs.msg import String
from geometry_msgs.msg import Twist
from turtlesim.msg import Pose


class turtlebotMover:

    def __init__(self):
        pub_topic  = "/turtle1/cmd_vel"
        sub_topic = "/turtle1/pose"

        self.pub = rospy.Publisher(pub_topic, Twist, queue_size=10)
        self.subscriber = rospy.Subscriber(sub_topic, Pose, self.pose_callback)
        self.veloc_angle_msg = Twist()

    
    def pose_callback(self, msg):
        if (msg.x >= 7):
            self.veloc_angle_msg.linear.x = 0
            self.veloc_angle_msg.angular.z = 1
        else:
            self.veloc_angle_msg.linear.x = 0.5

        self.pub.publish(self.veloc_angle_msg)


if __name__ == "__main__":
    node_name = "TurtleTrial"
    rospy.init_node(node_name)
    turtlebotMover()
    rospy.spin()
